services:
  mysql:
      image: mysql
      container_name: mysql-go
      environment:
        MYSQL_ROOT_PASSWORD: password
      ports:
      - "3306:3306"
      networks:
      - rest-api-go
      volumes:
      - mysql-go:/var/lib/mysql

volumes:
  mysql-go:
    driver: local
  
networks:
  rest-api-go:
    driver: bridge
